/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Used to describe the format of the account.<br><br> See [Account Identification Combinations](https://docs.yapily.com/pages/key-concepts/payments/payment-execution/intro-to-payment-execution/#account-identifications-combinations) for more information.
*/
export enum AccountIdentificationTypeResponse {
    SortCode = 'SORT_CODE',
    AccountNumber = 'ACCOUNT_NUMBER',
    Iban = 'IBAN',
    Bban = 'BBAN',
    Bic = 'BIC',
    Pan = 'PAN',
    MaskedPan = 'MASKED_PAN',
    Msisdn = 'MSISDN',
    Bsb = 'BSB',
    Ncc = 'NCC',
    Aba = 'ABA',
    AbaWire = 'ABA_WIRE',
    AbaAch = 'ABA_ACH',
    Email = 'EMAIL',
    RollNumber = 'ROLL_NUMBER',
    Blz = 'BLZ',
    Ifs = 'IFS',
    Clabe = 'CLABE',
    Ctn = 'CTN',
    BranchCode = 'BRANCH_CODE',
    VirtualAccountId = 'VIRTUAL_ACCOUNT_ID'
}
