/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountBalanceType } from '../models/AccountBalanceType';
import { Amount } from '../models/Amount';
import { CreditLine } from '../models/CreditLine';
import { HttpFile } from '../http/http';

export class AccountBalance {
  'type'?: AccountBalanceType;
  /**
   * Date and time of the reported balance.
   */
  'dateTime'?: Date;
  'balanceAmount'?: Amount;
  /**
   * _Optional_. Indicates whether any credit lines are included in the balance.
   */
  'creditLineIncluded'?: boolean;
  /**
   * _Optional_. Specifies the type of balance.
   */
  'creditLines'?: Array<CreditLine>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'AccountBalanceType',
      format: '',
    },
    {
      name: 'dateTime',
      baseName: 'dateTime',
      type: 'Date',
      format: 'date-time',
    },
    {
      name: 'balanceAmount',
      baseName: 'balanceAmount',
      type: 'Amount',
      format: '',
    },
    {
      name: 'creditLineIncluded',
      baseName: 'creditLineIncluded',
      type: 'boolean',
      format: '',
    },
    {
      name: 'creditLines',
      baseName: 'creditLines',
      type: 'Array<CreditLine>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return AccountBalance.attributeTypeMap;
  }

  public constructor() {}
}
