/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstitutionError } from '../models/InstitutionError';
import { HttpFile } from '../http/http';

/**
* Provides details of the error that has occurred.
*/
export class ApiError {
    /**
    * _Mandatory_. Numeric `HTTP` status code associated with the error.
    */
    'code'?: number;
    'institutionError'?: InstitutionError;
    /**
    * __Mandatory__. Description of the exact error that has been experienced.
    */
    'message'?: string;
    'source'?: string;
    /**
    * __Mandatory__. Textual description of the `HTTP` error status type.
    */
    'status'?: string;
    /**
    * _Optional_.  A unique identifier assigned by Yapily for the request that can be used for support purposes.
    */
    'tracingId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "institutionError",
            "baseName": "institutionError",
            "type": "InstitutionError",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tracingId",
            "baseName": "tracingId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiError.attributeTypeMap;
    }

    public constructor() {
    }
}

