/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiListResponseOfRealTimeTransactionLinks } from '../models/ApiListResponseOfRealTimeTransactionLinks';
import { RawResponse } from '../models/RawResponse';
import { RealTimeTransaction } from '../models/RealTimeTransaction';
import { ResponseForwardedData } from '../models/ResponseForwardedData';
import { ResponseMetaWithCount } from '../models/ResponseMetaWithCount';
import { HttpFile } from '../http/http';

export class ApiListResponseOfRealTimeTransaction {
    'meta'?: ResponseMetaWithCount;
    'data'?: Array<RealTimeTransaction>;
    'links'?: ApiListResponseOfRealTimeTransactionLinks;
    'forwardedData'?: Array<ResponseForwardedData>;
    'raw'?: Array<RawResponse>;
    'tracingId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "ResponseMetaWithCount",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<RealTimeTransaction>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ApiListResponseOfRealTimeTransactionLinks",
            "format": ""
        },
        {
            "name": "forwardedData",
            "baseName": "forwardedData",
            "type": "Array<ResponseForwardedData>",
            "format": ""
        },
        {
            "name": "raw",
            "baseName": "raw",
            "type": "Array<RawResponse>",
            "format": ""
        },
        {
            "name": "tracingId",
            "baseName": "tracingId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiListResponseOfRealTimeTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}

