/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Institution } from '../models/Institution';
import { Media } from '../models/Media';
import { HttpFile } from '../http/http';

/**
* Information about the application.
*/
export class Application {
    /**
    * Unique identification for the `Application` as assigned by Yapily.
    */
    'uuid'?: string;
    /**
    * The individual name of the `Application`.
    */
    'name'?: string;
    /**
    * States whether an `Application` is active.
    */
    'active'?: boolean;
    'authCallbacks'?: Array<string>;
    'institutions'?: Set<Institution>;
    'media'?: Set<Media>;
    /**
    * Date and time of when the application was created.
    */
    'created'?: Date;
    /**
    * Date and time of when the application was last updated.
    */
    'updated'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "authCallbacks",
            "baseName": "authCallbacks",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "institutions",
            "baseName": "institutions",
            "type": "Set<Institution>",
            "format": ""
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "Set<Media>",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Application.attributeTypeMap;
    }

    public constructor() {
    }
}

