/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationResponseListMetaPagination } from '../models/ApplicationResponseListMetaPagination';
import { HttpFile } from '../http/http';

export class ApplicationResponseListMeta {
    'tracingId'?: string;
    /**
    * The number of applications in the current page.
    */
    'count'?: number;
    'pagination'?: ApplicationResponseListMetaPagination;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tracingId",
            "baseName": "tracingId",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "ApplicationResponseListMetaPagination",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationResponseListMeta.attributeTypeMap;
    }

    public constructor() {
    }
}

