/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnrichedBalances } from '../models/EnrichedBalances';
import { ProfileConsent } from '../models/ProfileConsent';
import { HttpFile } from '../http/http';

/**
* A Balance Prediction profile for a User.
*/
export class BalancePredictionProfile {
    /**
    * The status, will be COMPLETED which represents successful retreival of profile.
    */
    'status'?: string;
    /**
    * A list of ProfileConsents used in the Balance Prediction profile.
    */
    'profileConsents'?: Array<ProfileConsent>;
    /**
    * A list of Balances returned by Balance Prediction profile.
    */
    'enrichedBalances'?: Array<EnrichedBalances>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileConsents",
            "baseName": "profileConsents",
            "type": "Array<ProfileConsent>",
            "format": ""
        },
        {
            "name": "enrichedBalances",
            "baseName": "enrichedBalances",
            "type": "Array<EnrichedBalances>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BalancePredictionProfile.attributeTypeMap;
    }

    public constructor() {
    }
}

