/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BeneficiaryPayee } from '../models/BeneficiaryPayee';
import { HttpFile } from '../http/http';

/**
* Account information belonging to the target beneficiary (person/ business).
*/
export class Beneficiary {
    /**
    * Unique identifier of the `beneficiary`.
    */
    'id'?: string;
    /**
    * A creditor reference that is requested to be used for all payment instructions to this beneficiary.
    */
    'reference'?: string;
    'payee'?: BeneficiaryPayee;
    /**
    * Indicates whether the account owner has stated that this beneficiary should be trusted. This often results in reduced authentication and authorisation requirements on payments to the beneficiary.
    */
    'trusted'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "BeneficiaryPayee",
            "format": ""
        },
        {
            "name": "trusted",
            "baseName": "trusted",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Beneficiary.attributeTypeMap;
    }

    public constructor() {
    }
}

