/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComplianceDataBusiness } from '../models/ComplianceDataBusiness';
import { ComplianceDataIndividual } from '../models/ComplianceDataIndividual';
import { HttpFile } from '../http/http';

/**
* __Conditional__. Payer details required for compliance checks.
*/
export class ComplianceDataPayer {
    /**
    * The payer type. Allowed values: INDIVIDUAL, BUSINESS. The corresponding object must be included.
    */
    'type': string;
    'individual'?: ComplianceDataIndividual;
    'business'?: ComplianceDataBusiness;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "individual",
            "baseName": "individual",
            "type": "ComplianceDataIndividual",
            "format": ""
        },
        {
            "name": "business",
            "baseName": "business",
            "type": "ComplianceDataBusiness",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComplianceDataPayer.attributeTypeMap;
    }

    public constructor() {
    }
}

