/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthorisationStatus } from '../models/AuthorisationStatus';
import { FeatureEnum } from '../models/FeatureEnum';
import { HttpFile } from '../http/http';

/**
* Consent detailing the requested authorisation from a user to a specific `Institution`.
*/
export class Consent {
    /**
    * Unique identifier of the consent.
    */
    'id'?: string;
    'userUuid'?: string;
    /**
    * __Conditional__. The user-friendly reference to the `User` that will authorise the authorisation request. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
    */
    'applicationUserId'?: string;
    'referenceId'?: string;
    /**
    * __Mandatory__. The `Institution` the authorisation request is sent to.
    */
    'institutionId'?: string;
    'status'?: AuthorisationStatus;
    /**
    * Date and time of when the consent was created.
    */
    'createdAt'?: Date;
    /**
    * When performing a transaction query using the consent, this is the earliest date of transaction records that can be retrieved.
    */
    'transactionFrom'?: Date;
    /**
    * When performing a transaction query using the consent, this is the latest date of transaction records that can be retrieved.
    */
    'transactionTo'?: Date;
    /**
    * Date and time of when the authorisation will expire by. Reauthorisation will be needed to retain access.
    */
    'expiresAt'?: Date;
    'timeToExpireInMillis'?: number;
    'timeToExpire'?: string;
    /**
    * The set of features that the consent will provide access to.
    */
    'featureScope'?: Set<FeatureEnum>;
    /**
    * Represents the authorisation to gain access to the requested features. Required to access account information or make a payment request.
    */
    'consentToken'?: string;
    /**
    * Correlation ID used with the `Institution` during the authorisation process.
    */
    'state'?: string;
    /**
    * Date and time of when the request was authorised by the Institution.
    */
    'authorizedAt'?: Date;
    /**
    * The time that the PSU last confirmed access to their account information, either through full authentication with the institution, or through reconfirmation with the TPP.
    */
    'lastConfirmedAt'?: Date;
    /**
    * The time by which the consent should be reconfirmed to ensure continued access to the account information.
    */
    'reconfirmBy'?: Date;
    /**
    * Identification of the consent at the Institution.
    */
    'institutionConsentId'?: string;
    /**
    * Denotes whether the consent has been deleted on the institution side or not when a DELETE method is executed on a Yapily consent if that functionality is provided by the institution
    */
    'isDeletedByInstitution'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userUuid",
            "baseName": "userUuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "applicationUserId",
            "baseName": "applicationUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "referenceId",
            "baseName": "referenceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "institutionId",
            "baseName": "institutionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AuthorisationStatus",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "transactionFrom",
            "baseName": "transactionFrom",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "transactionTo",
            "baseName": "transactionTo",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "timeToExpireInMillis",
            "baseName": "timeToExpireInMillis",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timeToExpire",
            "baseName": "timeToExpire",
            "type": "string",
            "format": "iso8601"
        },
        {
            "name": "featureScope",
            "baseName": "featureScope",
            "type": "Set<FeatureEnum>",
            "format": ""
        },
        {
            "name": "consentToken",
            "baseName": "consentToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorizedAt",
            "baseName": "authorizedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastConfirmedAt",
            "baseName": "lastConfirmedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reconfirmBy",
            "baseName": "reconfirmBy",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "institutionConsentId",
            "baseName": "institutionConsentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDeletedByInstitution",
            "baseName": "isDeletedByInstitution",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Consent.attributeTypeMap;
    }

    public constructor() {
    }
}



