/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HostedPaymentRequestDetails } from '../models/HostedPaymentRequestDetails';
import { InstitutionIdentifiers } from '../models/InstitutionIdentifiers';
import { UserSettings } from '../models/UserSettings';
import { HttpFile } from '../http/http';

export class CreateHostedPaymentRequest {
    /**
    * __Conditional__. Yapily Identifier for the `User` returned by the create user step POST /users. You must provide either a `userId` or `applicationUserId`.
    */
    'userId'?: string;
    /**
    * __Conditional__. Your own `User` reference. This field allows you to use your own unique references for individual users. Where the `User` reference doesn\'t have an associated Yapily `userId`, a new `userId` is created and linked to it. You must provide either a `userId` or `applicationUserId`.
    */
    'applicationUserId'?: string;
    'institutionIdentifiers': InstitutionIdentifiers;
    'userSettings'?: UserSettings;
    /**
    * URL of your server to redirect the user after completion of the payment flow.
    */
    'redirectUrl': string;
    'paymentRequestDetails': HostedPaymentRequestDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "applicationUserId",
            "baseName": "applicationUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "institutionIdentifiers",
            "baseName": "institutionIdentifiers",
            "type": "InstitutionIdentifiers",
            "format": ""
        },
        {
            "name": "userSettings",
            "baseName": "userSettings",
            "type": "UserSettings",
            "format": ""
        },
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentRequestDetails",
            "baseName": "paymentRequestDetails",
            "type": "HostedPaymentRequestDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateHostedPaymentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

