/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstitutionIdentifiers } from '../models/InstitutionIdentifiers';
import { UserSettings } from '../models/UserSettings';
import { VRPSetupRequest } from '../models/VRPSetupRequest';
import { HttpFile } from '../http/http';

export class CreateHostedVRPConsentRequest {
    /**
    * __Conditional__. Yapily Identifier for the `User` returned by the create user step POST /users. Clients must either provide userId or applicationUserId.
    */
    'userId'?: string;
    /**
    * __Conditional__. Client\'s own `User` reference. If the client wants to work with their own unique references for individual PSUs then they can use the applicationUserId property to provide that value. Where Yapily does not already have a Yapily userId that matches the supplied applicationUserId, then a new Yapily userId is created automatically and linked to the applicationUserId value. Clients must either provide userId or applicationUserId.
    */
    'applicationUserId'?: string;
    'institutionIdentifiers': InstitutionIdentifiers;
    'userSettings'?: UserSettings;
    /**
    * URL of client\'s server to redirect the PSU after completion of the consent authorisation.
    */
    'redirectUrl': string;
    /**
    * Used to receive a oneTimeToken rather than a consentToken at the redirectUrl for additional security. This can only be used when the redirectUrl is set.
    */
    'oneTimeToken'?: boolean;
    'vrpSetup': VRPSetupRequest;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "applicationUserId",
            "baseName": "applicationUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "institutionIdentifiers",
            "baseName": "institutionIdentifiers",
            "type": "InstitutionIdentifiers",
            "format": ""
        },
        {
            "name": "userSettings",
            "baseName": "userSettings",
            "type": "UserSettings",
            "format": ""
        },
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "oneTimeToken",
            "baseName": "oneTimeToken",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vrpSetup",
            "baseName": "vrpSetup",
            "type": "VRPSetupRequest",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateHostedVRPConsentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

