/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The type of credentials required to register the `Institution`
*/
export enum CredentialsType {
    Oauth1 = 'OAUTH1',
    Oauth2 = 'OAUTH2',
    Oauth2Nosecret = 'OAUTH2_NOSECRET',
    Oauth2Signature = 'OAUTH2_SIGNATURE',
    OpenBankingUkManual = 'OPEN_BANKING_UK_MANUAL',
    OpenBankingUkAuto = 'OPEN_BANKING_UK_AUTO',
    OpenBankingIbm = 'OPEN_BANKING_IBM',
    OpenBankingAuto = 'OPEN_BANKING_AUTO',
    OpenBankingAutoEmail = 'OPEN_BANKING_AUTO_EMAIL',
    OpenBankingManual = 'OPEN_BANKING_MANUAL',
    OpenBankingWithTppIdAndSecret = 'OPEN_BANKING_WITH_TPP_ID_AND_SECRET',
    ApiKey = 'API_KEY',
    OpenBankingNoKey = 'OPEN_BANKING_NO_KEY',
    OpenBankingNoTransport = 'OPEN_BANKING_NO_TRANSPORT',
    TokenIo = 'TOKEN_IO'
}
