/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Provides details on the currrency exchange.
*/
export class CurrencyExchange {
    /**
    * Currency from which an amount is to be converted.
    */
    'sourceCurrency'?: string;
    /**
    * Currency to which an amount is to be converted.
    */
    'targetCurrency'?: string;
    /**
    * The currency in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is GBP.
    */
    'unitCurrency'?: string;
    /**
    * The factor used for conversion of an amount from one currency to another. This reflects the price at which one currency was bought with another currency.
    */
    'exchangeRate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sourceCurrency",
            "baseName": "sourceCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetCurrency",
            "baseName": "targetCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitCurrency",
            "baseName": "unitCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "exchangeRate",
            "baseName": "exchangeRate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CurrencyExchange.attributeTypeMap;
    }

    public constructor() {
    }
}

