/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestConstraints } from '../models/RequestConstraints';
import { HttpFile } from '../http/http';

export class DataConstraintsResponse {
    /**
    * The id to represent the `Institution`.
    */
    'institutionId': string;
    /**
    * 2 letter ISO Country code of the `Institution`.
    */
    'institutionCountryCode'?: string;
    /**
    * Define the applicable API end point.
    */
    'endpointPath'?: string;
    /**
    * Https Method for the endpoint.
    */
    'endpointMethod'?: string;
    'request': RequestConstraints;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "institutionId",
            "baseName": "institutionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "institutionCountryCode",
            "baseName": "institutionCountryCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpointPath",
            "baseName": "endpointPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpointMethod",
            "baseName": "endpointMethod",
            "type": "string",
            "format": ""
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "RequestConstraints",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DataConstraintsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

