/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { DirectDebitPayee } from '../models/DirectDebitPayee';
import { PaymentStatusDetails } from '../models/PaymentStatusDetails';
import { HttpFile } from '../http/http';

export class DirectDebitResponse {
    'id'?: string;
    'statusDetails'?: PaymentStatusDetails;
    'payeeDetails'?: DirectDebitPayee;
    'reference'?: string;
    'previousPaymentAmount'?: Amount;
    'previousPaymentDateTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusDetails",
            "baseName": "statusDetails",
            "type": "PaymentStatusDetails",
            "format": ""
        },
        {
            "name": "payeeDetails",
            "baseName": "payeeDetails",
            "type": "DirectDebitPayee",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousPaymentAmount",
            "baseName": "previousPaymentAmount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "previousPaymentDateTime",
            "baseName": "previousPaymentDateTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return DirectDebitResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

