/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A list of Predicted Account Balances for future date range.
*/
export class EnrichedPredictedBalance {
    /**
    * The date for which Balance amount is predicted.
    */
    'date'?: string;
    /**
    * The median Balance amount for a future date.
    */
    'medianBalance'?: number;
    /**
    * The 90th percentile Balance amount for a future date.
    */
    '_90percentileBalance'?: number;
    /**
    * The 10th percentile Balance amount for a future date.
    */
    '_10percentileBalance'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "medianBalance",
            "baseName": "medianBalance",
            "type": "number",
            "format": ""
        },
        {
            "name": "_90percentileBalance",
            "baseName": "90percentileBalance",
            "type": "number",
            "format": ""
        },
        {
            "name": "_10percentileBalance",
            "baseName": "10percentileBalance",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnrichedPredictedBalance.attributeTypeMap;
    }

    public constructor() {
    }
}

