/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnrichedHistoricBalance } from '../models/EnrichedHistoricBalance';
import { EnrichedPredictedBalance } from '../models/EnrichedPredictedBalance';
import { HttpFile } from '../http/http';

/**
* Enriched Balance information generated which include historic aggregated balances and predicted balances
*/
export class EnrichedBalances {
    /**
    * A list of Account Ids used to generate Balance Prediction Profile.
    */
    'accountIds'?: Array<string>;
    /**
    * A list of Institution Ids associated with the accounts used to generate Balance Prediction Profile.
    */
    'institutions'?: Array<string>;
    /**
    * A list of historic balances. Each balance in the list is an aggregation (sum) of the reported balance for each account within the profile at a point in time.
    */
    'historic'?: Array<EnrichedHistoricBalance>;
    /**
    * A list of predicted balances. Each balance in the list is a projected balance of the profile at a future point in time.
    */
    'predicted'?: Array<EnrichedPredictedBalance>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountIds",
            "baseName": "accountIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "institutions",
            "baseName": "institutions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "historic",
            "baseName": "historic",
            "type": "Array<EnrichedHistoricBalance>",
            "format": ""
        },
        {
            "name": "predicted",
            "baseName": "predicted",
            "type": "Array<EnrichedPredictedBalance>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnrichedBalances.attributeTypeMap;
    }

    public constructor() {
    }
}

