/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TerminatedTransactionStream } from '../models/TerminatedTransactionStream';
import { TransactionStream } from '../models/TransactionStream';
import { HttpFile } from '../http/http';

/**
* Details of income and expenditure streams, identified by Yapily data services.
*/
export class EnrichedWrapper {
    /**
    * Lists all possible income streams identified for the `Application User`.
    */
    'incomeStreams': Array<TransactionStream>;
    /**
    * Lists all possible expenditure streams identified for the `Application User`.
    */
    'expenditureStreams': Array<TransactionStream>;
    /**
    * A list of terminated transaction income streams
    */
    'recentlyTerminatedIncomeStreams': Array<TerminatedTransactionStream>;
    /**
    * A list of terminated transaction expenditure streams
    */
    'recentlyTerminatedExpenditureStreams': Array<TerminatedTransactionStream>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "incomeStreams",
            "baseName": "incomeStreams",
            "type": "Array<TransactionStream>",
            "format": ""
        },
        {
            "name": "expenditureStreams",
            "baseName": "expenditureStreams",
            "type": "Array<TransactionStream>",
            "format": ""
        },
        {
            "name": "recentlyTerminatedIncomeStreams",
            "baseName": "recentlyTerminatedIncomeStreams",
            "type": "Array<TerminatedTransactionStream>",
            "format": ""
        },
        {
            "name": "recentlyTerminatedExpenditureStreams",
            "baseName": "recentlyTerminatedExpenditureStreams",
            "type": "Array<TerminatedTransactionStream>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnrichedWrapper.attributeTypeMap;
    }

    public constructor() {
    }
}

