/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Details of the transaction, identified by Yapily data services.
*/
export class EnrichedTransaction {
    /**
    * Unique identifier of the transaction
    */
    'transactionId'?: string;
    /**
    * Information for the transaction
    */
    'transactionInformation'?: string;
    /**
    * Monetary amount.
    */
    'amount'?: number;
    /**
    * The `Institution` that the transaction is sent to.
    */
    'institution'?: string;
    /**
    * Date and time of when a transaction entry occured and was posted to the account servicer\'s books.
    */
    'bookingDateTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionInformation",
            "baseName": "transactionInformation",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "institution",
            "baseName": "institution",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookingDateTime",
            "baseName": "bookingDateTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return EnrichedTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}

