/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Details of the merchant, identified by Yapily data services.
*/
export class EnrichmentMerchant {
    /**
    * The name of the indivdual merchant involved in the transaction e.g. (TESCO Petrol).
    */
    'merchantName'?: string;
    /**
    * The parent organisation that the merchant belongs to e.g. (TESCO).
    */
    'parentGroup'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "merchantName",
            "baseName": "merchantName",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentGroup",
            "baseName": "parentGroup",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnrichmentMerchant.attributeTypeMap;
    }

    public constructor() {
    }
}

