/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstitutionError } from '../models/InstitutionError';
import { HttpFile } from '../http/http';

/**
* Detailed information regarding the issue that was experienced during processing of the request
*/
export class ErrorIssue {
    /**
    * Category of the issue
    */
    'type': string;
    /**
    * Code that uniquely identifies the type of issue
    */
    'code': string;
    /**
    * Identfies the parameter / property within the request (headers, query parameters or body) that the issue relates to. For headers and query parameters, it refers to the parameter name. For the body, it refers to the JSONPath of the property
    */
    'parameter'?: string;
    /**
    * Human readable description of the issue that was experienced
    */
    'message'?: string;
    'institutionError'?: InstitutionError;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "parameter",
            "baseName": "parameter",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "institutionError",
            "baseName": "institutionError",
            "type": "InstitutionError",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorIssue.attributeTypeMap;
    }

    public constructor() {
    }
}

