/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorIssue } from '../models/ErrorIssue';
import { HttpFile } from '../http/http';

export class ErrorDetails {
    /**
    * Unique identifier of the request, used by Yapily for support purposes
    */
    'tracingId': string;
    /**
    * Numeric HTTP status code associated with the error
    */
    'code': number;
    /**
    * Textual description of the HTTP status
    */
    'status': string;
    /**
    * Link to where further information regarding the error can be found
    */
    'supportUrl'?: string;
    /**
    * Source of the error. This may be YAPILY, the INSTITUTION, or the USER
    */
    'source'?: string;
    /**
    * List of issues relating to the error
    */
    'issues'?: Array<ErrorIssue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tracingId",
            "baseName": "tracingId",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "supportUrl",
            "baseName": "supportUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<ErrorIssue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

