/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RateTypeEnum } from '../models/RateTypeEnum';
import { HttpFile } from '../http/http';

export class ExchangeRateInformationResponse {
    /**
    * __Mandatory__. The currency in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is `GBP`.
    */
    'unitCurrency': string;
    /**
    * __Optional__. The factor used for conversion of an amount from one currency to another. This reflects the price at which one currency was bought with another currency.
    */
    'rate'?: number;
    'rateType': RateTypeEnum;
    /**
    * __Optional__. The unique and unambiguous reference to the foreign exchange contract agreed between the initiating party/creditor and the debtor agent.
    */
    'foreignExchangeContractReference'?: string;
    'exchangeRateExpiryDate'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "unitCurrency",
            "baseName": "unitCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "RateTypeEnum",
            "format": ""
        },
        {
            "name": "foreignExchangeContractReference",
            "baseName": "foreignExchangeContractReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "exchangeRateExpiryDate",
            "baseName": "exchangeRateExpiryDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ExchangeRateInformationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



