/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Used to describe what functions are supported by the associated `Institution`.        <br><br>For more information on each feature, see the following links:        <ul>          <li>[Financial Data Features](https://docs.yapily.com/pages/key-concepts/account-data/account-features/)</li>          <li>[Payments Features](https://docs.yapily.com/pages/key-concepts/payments/payment-features/)</li>        </ul>
*/
export enum FeatureEnum {
    InitiatePreAuthorisation = 'INITIATE_PRE_AUTHORISATION',
    InitiatePreAuthorisationAccounts = 'INITIATE_PRE_AUTHORISATION_ACCOUNTS',
    InitiatePreAuthorisationPayments = 'INITIATE_PRE_AUTHORISATION_PAYMENTS',
    InitiateAccountRequest = 'INITIATE_ACCOUNT_REQUEST',
    InitiateEmbeddedAccountRequest = 'INITIATE_EMBEDDED_ACCOUNT_REQUEST',
    AccountRequestDetails = 'ACCOUNT_REQUEST_DETAILS',
    Accounts = 'ACCOUNTS',
    Account = 'ACCOUNT',
    AccountTransactions = 'ACCOUNT_TRANSACTIONS',
    AccountStatements = 'ACCOUNT_STATEMENTS',
    AccountStatement = 'ACCOUNT_STATEMENT',
    AccountStatementFile = 'ACCOUNT_STATEMENT_FILE',
    AccountScheduledPayments = 'ACCOUNT_SCHEDULED_PAYMENTS',
    AccountDirectDebits = 'ACCOUNT_DIRECT_DEBITS',
    AccountPeriodicPayments = 'ACCOUNT_PERIODIC_PAYMENTS',
    AccountTransactionsWithMerchant = 'ACCOUNT_TRANSACTIONS_WITH_MERCHANT',
    Identity = 'IDENTITY',
    AccountsWithoutBalance = 'ACCOUNTS_WITHOUT_BALANCE',
    AccountWithoutBalance = 'ACCOUNT_WITHOUT_BALANCE',
    AccountBalances = 'ACCOUNT_BALANCES',
    InitiateSinglePaymentSortcode = 'INITIATE_SINGLE_PAYMENT_SORTCODE',
    ExistingPaymentInitiationDetails = 'EXISTING_PAYMENT_INITIATION_DETAILS',
    CreateSinglePaymentSortcode = 'CREATE_SINGLE_PAYMENT_SORTCODE',
    ExistingPaymentsDetails = 'EXISTING_PAYMENTS_DETAILS',
    InitiateDomesticSinglePayment = 'INITIATE_DOMESTIC_SINGLE_PAYMENT',
    InitiateEmbeddedDomesticSinglePayment = 'INITIATE_EMBEDDED_DOMESTIC_SINGLE_PAYMENT',
    CreateDomesticSinglePayment = 'CREATE_DOMESTIC_SINGLE_PAYMENT',
    InitiateEmbeddedBulkPayment = 'INITIATE_EMBEDDED_BULK_PAYMENT',
    InitiateDomesticSingleInstantPayment = 'INITIATE_DOMESTIC_SINGLE_INSTANT_PAYMENT',
    CreateDomesticSingleInstantPayment = 'CREATE_DOMESTIC_SINGLE_INSTANT_PAYMENT',
    InitiateDomesticVariableRecurringPayment = 'INITIATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT',
    CreateDomesticVariableRecurringPayment = 'CREATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT',
    InitiateDomesticVariableRecurringPaymentSweeping = 'INITIATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT_SWEEPING',
    InitiateDomesticVariableRecurringPaymentNonsweeping = 'INITIATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT_NONSWEEPING',
    CreateDomesticVariableRecurringPaymentSweeping = 'CREATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT_SWEEPING',
    CreateDomesticVariableRecurringPaymentNonsweeping = 'CREATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT_NONSWEEPING',
    InitiateDomesticScheduledPayment = 'INITIATE_DOMESTIC_SCHEDULED_PAYMENT',
    CreateDomesticScheduledPayment = 'CREATE_DOMESTIC_SCHEDULED_PAYMENT',
    InitiateDomesticPeriodicPayment = 'INITIATE_DOMESTIC_PERIODIC_PAYMENT',
    CreateDomesticPeriodicPayment = 'CREATE_DOMESTIC_PERIODIC_PAYMENT',
    PeriodicPaymentFrequencyExtended = 'PERIODIC_PAYMENT_FREQUENCY_EXTENDED',
    InitiateInternationalScheduledPayment = 'INITIATE_INTERNATIONAL_SCHEDULED_PAYMENT',
    CreateInternationalScheduledPayment = 'CREATE_INTERNATIONAL_SCHEDULED_PAYMENT',
    InitiateInternationalPeriodicPayment = 'INITIATE_INTERNATIONAL_PERIODIC_PAYMENT',
    CreateInternationalPeriodicPayment = 'CREATE_INTERNATIONAL_PERIODIC_PAYMENT',
    InitiateInternationalSinglePayment = 'INITIATE_INTERNATIONAL_SINGLE_PAYMENT',
    CreateInternationalSinglePayment = 'CREATE_INTERNATIONAL_SINGLE_PAYMENT',
    InitiateBulkPayment = 'INITIATE_BULK_PAYMENT',
    CreateBulkPayment = 'CREATE_BULK_PAYMENT',
    Transfer = 'TRANSFER',
    OpenDataPersonalCurrentAccounts = 'OPEN_DATA_PERSONAL_CURRENT_ACCOUNTS',
    OpenDataAtms = 'OPEN_DATA_ATMS',
    ReadDomesticSingleRefund = 'READ_DOMESTIC_SINGLE_REFUND',
    ReadDomesticScheduledRefund = 'READ_DOMESTIC_SCHEDULED_REFUND',
    ReadDomesticPeriodicPaymentRefund = 'READ_DOMESTIC_PERIODIC_PAYMENT_REFUND',
    ReadInternationalSingleRefund = 'READ_INTERNATIONAL_SINGLE_REFUND',
    ReadInternationalScheduledRefund = 'READ_INTERNATIONAL_SCHEDULED_REFUND',
    AccountBeneficiaries = 'ACCOUNT_BENEFICIARIES',
    InitiateOnetimePreAuthorisationPayments = 'INITIATE_ONETIME_PRE_AUTHORISATION_PAYMENTS',
    InitiateOnetimePreAuthorisationAccounts = 'INITIATE_ONETIME_PRE_AUTHORISATION_ACCOUNTS',
    InitiateOnetimePreAuthorisation = 'INITIATE_ONETIME_PRE_AUTHORISATION',
    VariableRecurringPaymentFundsConfirmation = 'VARIABLE_RECURRING_PAYMENT_FUNDS_CONFIRMATION'
}
