/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SortEnum } from '../models/SortEnum';
import { HttpFile } from '../http/http';

export class FilterAndSort {
    /**
    * __Optional__. The earliest date and time of resources / records that should be returned.
    */
    '_from'?: Date;
    /**
    * __Optional__. The latest date and time of resources / records that should be returned.
    */
    'before'?: Date;
    /**
    * __Optional__. The maximum number of resources / records that should be returned.
    */
    'limit'?: number;
    'sort'?: SortEnum;
    'offset'?: number;
    'cursor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_from",
            "baseName": "from",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "before",
            "baseName": "before",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "SortEnum",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FilterAndSort.attributeTypeMap;
    }

    public constructor() {
    }
}



