/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { HttpFile } from '../http/http';

/**
* The fund confirmation object defining the details of the account and funds to be checked under the Variable Recurring Payment consent.
*/
export class FundsConfirmationRequest {
    /**
    * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
    */
    'reference'?: string;
    'paymentAmount': Amount;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentAmount",
            "baseName": "paymentAmount",
            "type": "Amount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FundsConfirmationRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

