/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstitutionIdentifiers } from '../models/InstitutionIdentifiers';
import { VRPSetupRequest } from '../models/VRPSetupRequest';
import { HttpFile } from '../http/http';

export class GetHostedVRPConsentsResponseInner {
    /**
    * Represents the Unique Id of the VRP consent request
    */
    'id': string;
    /**
    * Represents the Unique Id of the `Application` the user is associated with.
    */
    'applicationId': string;
    'institutionIdentifiers'?: InstitutionIdentifiers;
    'vrpSetup'?: VRPSetupRequest;
    /**
    * Represents the date and time at which the Consent was updated.
    */
    'updatedAt'?: Date;
    /**
    * Current status of the authorisation. Can be one of [AWAITING_AUTHORIZATION, AUTHORIZED, REJECTED, REVOKED, FAILED, EXPIRED]
    */
    'consentStatus'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "applicationId",
            "baseName": "applicationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "institutionIdentifiers",
            "baseName": "institutionIdentifiers",
            "type": "InstitutionIdentifiers",
            "format": ""
        },
        {
            "name": "vrpSetup",
            "baseName": "vrpSetup",
            "type": "VRPSetupRequest",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "consentStatus",
            "baseName": "consentStatus",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetHostedVRPConsentsResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}

