/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { HostedPaymentStatusDetails } from '../models/HostedPaymentStatusDetails';
import { HostedVrpPayerResponse } from '../models/HostedVrpPayerResponse';
import { HostedVrpRefundAccount } from '../models/HostedVrpRefundAccount';
import { Payee } from '../models/Payee';
import { PaymentRisk } from '../models/PaymentRisk';
import { HttpFile } from '../http/http';

export class HostedVRPPaymentResponse {
    'id'?: string;
    'paymentIdempotencyId'?: string;
    'amount'?: Amount;
    /**
    * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
    */
    'reference'?: string;
    'payee'?: Payee;
    'payer'?: HostedVrpPayerResponse;
    'refundAccount'?: HostedVrpRefundAccount;
    'risk'?: PaymentRisk;
    /**
    * The Unique Identifier provided by TPP in the Payment request to identify the payment.
    */
    'paymentLifecycleId'?: string;
    'expectedExecutionTime'?: Date;
    'expectedSettlementTime'?: Date;
    'institutionPaymentId'?: string;
    'statusDetails'?: HostedPaymentStatusDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentIdempotencyId",
            "baseName": "paymentIdempotencyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "Payee",
            "format": ""
        },
        {
            "name": "payer",
            "baseName": "payer",
            "type": "HostedVrpPayerResponse",
            "format": ""
        },
        {
            "name": "refundAccount",
            "baseName": "refundAccount",
            "type": "HostedVrpRefundAccount",
            "format": ""
        },
        {
            "name": "risk",
            "baseName": "risk",
            "type": "PaymentRisk",
            "format": ""
        },
        {
            "name": "paymentLifecycleId",
            "baseName": "paymentLifecycleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "expectedExecutionTime",
            "baseName": "expectedExecutionTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expectedSettlementTime",
            "baseName": "expectedSettlementTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "institutionPaymentId",
            "baseName": "institutionPaymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusDetails",
            "baseName": "statusDetails",
            "type": "HostedPaymentStatusDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HostedVRPPaymentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

