/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HostedPaymentIsoStatus } from '../models/HostedPaymentIsoStatus';
import { PaymentStatus } from '../models/PaymentStatus';
import { HttpFile } from '../http/http';

/**
* The status of the payment.
*/
export class HostedPaymentStatusDetails {
    'status'?: PaymentStatus;
    /**
    * Date and time the status was updated.
    */
    'statusUpdateDate'?: Date;
    'isoStatus'?: HostedPaymentIsoStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentStatus",
            "format": ""
        },
        {
            "name": "statusUpdateDate",
            "baseName": "statusUpdateDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isoStatus",
            "baseName": "isoStatus",
            "type": "HostedPaymentIsoStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HostedPaymentStatusDetails.attributeTypeMap;
    }

    public constructor() {
    }
}



