/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HostedPayment } from '../models/HostedPayment';
import { HostedPaymentRequestDetailsLink } from '../models/HostedPaymentRequestDetailsLink';
import { InstitutionIdentifiersResponse } from '../models/InstitutionIdentifiersResponse';
import { UserSettings } from '../models/UserSettings';
import { HttpFile } from '../http/http';

export class HostedPaymentDetails {
    /**
    * The unique ID of the payment request.
    */
    'paymentRequestId'?: string;
    /**
    * The Unique Identifier for the `User` assigned by Yapily.
    */
    'userId'?: string;
    /**
    * Your reference to the `User`.
    */
    'applicationUserId'?: string;
    /**
    * The Unique Identifier of the `Application` the user is associated with.
    */
    'applicationId'?: string;
    'institutionIdentifiers'?: InstitutionIdentifiersResponse;
    'userSettings'?: UserSettings;
    /**
    * URL of your server to redirect the user after completion of the payment flow.
    */
    'redirectUrl'?: string;
    'paymentRequestDetails'?: HostedPaymentRequestDetailsLink;
    /**
    * The date and time at which the payment request was created.
    */
    'createdAt'?: Date;
    /**
    * The date and time at which the auth Token will expire.
    */
    'authorisationExpiresAt'?: Date;
    /**
    * Current status of the payment request. <br> Possible values: <br> ACTIVE <br> INACTIVE
    */
    'status'?: string;
    /**
    * Payments that have been initiated as part of this request
    */
    'payments'?: Set<HostedPayment>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentRequestId",
            "baseName": "paymentRequestId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "applicationUserId",
            "baseName": "applicationUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "applicationId",
            "baseName": "applicationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "institutionIdentifiers",
            "baseName": "institutionIdentifiers",
            "type": "InstitutionIdentifiersResponse",
            "format": ""
        },
        {
            "name": "userSettings",
            "baseName": "userSettings",
            "type": "UserSettings",
            "format": ""
        },
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentRequestDetails",
            "baseName": "paymentRequestDetails",
            "type": "HostedPaymentRequestDetailsLink",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "authorisationExpiresAt",
            "baseName": "authorisationExpiresAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Set<HostedPayment>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HostedPaymentDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

