/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountDetailsResponse } from '../models/AmountDetailsResponse';
import { PayeeDetailsResponse } from '../models/PayeeDetailsResponse';
import { PayerDetailsResponse } from '../models/PayerDetailsResponse';
import { PaymentContextTypeResponse } from '../models/PaymentContextTypeResponse';
import { PaymentTypeResponse } from '../models/PaymentTypeResponse';
import { HttpFile } from '../http/http';

export class HostedPaymentRequestDetailsLink {
    /**
    * The payment reference or description. Limited to a maximum of 18 characters for UK institutions.
    */
    'reference'?: string;
    'contextType'?: PaymentContextTypeResponse;
    'type'?: PaymentTypeResponse;
    'payee'?: PayeeDetailsResponse;
    'payer'?: PayerDetailsResponse;
    'amountDetails'?: AmountDetailsResponse;
    /**
    * The date that the payment is due. Displayed to the end user in the payment summary screen.
    */
    'paymentDueDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "contextType",
            "baseName": "contextType",
            "type": "PaymentContextTypeResponse",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentTypeResponse",
            "format": ""
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "PayeeDetailsResponse",
            "format": ""
        },
        {
            "name": "payer",
            "baseName": "payer",
            "type": "PayerDetailsResponse",
            "format": ""
        },
        {
            "name": "amountDetails",
            "baseName": "amountDetails",
            "type": "AmountDetailsResponse",
            "format": ""
        },
        {
            "name": "paymentDueDate",
            "baseName": "paymentDueDate",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return HostedPaymentRequestDetailsLink.attributeTypeMap;
    }

    public constructor() {
    }
}



