/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Country } from '../models/Country';
import { CredentialsType } from '../models/CredentialsType';
import { EnvironmentType } from '../models/EnvironmentType';
import { FeatureEnum } from '../models/FeatureEnum';
import { Media } from '../models/Media';
import { MonitoringFeatureStatus } from '../models/MonitoringFeatureStatus';
import { HttpFile } from '../http/http';

/**
* Typically, a bank or business unit within a bank e.g. (AIB Business, AIB Ireland, AIB UK).
*/
export class Institution {
    /**
    * Unique identifier for the `Institution`.
    */
    'id'?: string;
    /**
    * The friendly name of the `Institution`.
    */
    'name'?: string;
    /**
    * The full name of the `Institution`.
    */
    'fullName'?: string;
    /**
    * An array of `Country` denoting which regions the `Institution` provides coverage for
    */
    'countries'?: Set<Country>;
    'environmentType'?: EnvironmentType;
    'credentialsType'?: CredentialsType;
    /**
    * Contains links to the logo and the icons for the `Institution`
    */
    'media'?: Set<Media>;
    'features'?: Set<FeatureEnum>;
    'monitoring'?: { [key: string]: MonitoringFeatureStatus; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fullName",
            "baseName": "fullName",
            "type": "string",
            "format": ""
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Set<Country>",
            "format": ""
        },
        {
            "name": "environmentType",
            "baseName": "environmentType",
            "type": "EnvironmentType",
            "format": ""
        },
        {
            "name": "credentialsType",
            "baseName": "credentialsType",
            "type": "CredentialsType",
            "format": ""
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "Set<Media>",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Set<FeatureEnum>",
            "format": ""
        },
        {
            "name": "monitoring",
            "baseName": "monitoring",
            "type": "{ [key: string]: MonitoringFeatureStatus; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Institution.attributeTypeMap;
    }

    public constructor() {
    }
}



