/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Raw error details provided by the `Institution`, when it was the error source.
*/
export class InstitutionError {
    /**
    * Textual description of the `Institution` error.
    */
    'errorMessage'?: string;
    /**
    * Numeric HTTP status code associated with the `Institution` error.
    */
    'httpStatusCode'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "httpStatusCode",
            "baseName": "httpStatusCode",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return InstitutionError.attributeTypeMap;
    }

    public constructor() {
    }
}

