/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The status of the Payment. <br><br>For more information, see [Payment Status](/guides/payments/payment-status/)
*/
export enum PaymentStatus {
    Pending = 'PENDING',
    Failed = 'FAILED',
    Declined = 'DECLINED',
    Completed = 'COMPLETED',
    CompletedSettlementInProcess = 'COMPLETED_SETTLEMENT_IN_PROCESS',
    Expired = 'EXPIRED',
    Unknown = 'UNKNOWN',
    Active = 'ACTIVE',
    Inactive = 'INACTIVE'
}
