/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Specifies which of the [payment types](https://docs.yapily.com/pages/key-concepts/payments/payment-execution/intro-to-payment-execution/#payment-types) to execute.<br>
*/
export enum PaymentTypeResponse {
    DomesticPayment = 'DOMESTIC_PAYMENT',
    DomesticInstantPayment = 'DOMESTIC_INSTANT_PAYMENT',
    DomesticVariableRecurringPayment = 'DOMESTIC_VARIABLE_RECURRING_PAYMENT',
    DomesticScheduledPayment = 'DOMESTIC_SCHEDULED_PAYMENT',
    DomesticPeriodicPayment = 'DOMESTIC_PERIODIC_PAYMENT',
    InternationalPayment = 'INTERNATIONAL_PAYMENT',
    InternationalScheduledPayment = 'INTERNATIONAL_SCHEDULED_PAYMENT',
    InternationalPeriodicPayment = 'INTERNATIONAL_PERIODIC_PAYMENT',
    BulkPayment = 'BULK_PAYMENT'
}
