/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Details of a consent linked to a `User Profile`.
*/
export class ProfileConsent {
    /**
    * Unique identifier of the `consent` in context of a user\'s profile.
    */
    'id'?: string;
    /**
    * The status, can be PENDING, COMPLETED or ERROR.
    */
    'status'?: string;
    /**
    * The userUuid.
    */
    'userId'?: string;
    /**
    * Unique identifier of the consent.
    */
    'referenceConsentId'?: string;
    /**
    * __Mandatory__. The  `Institution` the authorisation request is sent to.
    */
    'institutionId'?: string;
    /**
    * When a profile consent is created.
    */
    'createdAt'?: Date;
    /**
    * When a profile consent is expired after created + X.
    */
    'expiresAt'?: Date;
    /**
    * After data retrieval from aggregated profile consent is completed.
    */
    'dataInsertedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "referenceConsentId",
            "baseName": "referenceConsentId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "institutionId",
            "baseName": "institutionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dataInsertedAt",
            "baseName": "dataInsertedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ProfileConsent.attributeTypeMap;
    }

    public constructor() {
    }
}

