/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RawRequest } from '../models/RawRequest';
import { HttpFile } from '../http/http';

/**
* Interaction (raw request and response) that occured with the `Institution` in order to fulfil a request.
*/
export class RawResponse {
    'request'?: RawRequest;
    'duration'?: string;
    'headers'?: { [key: string]: string; };
    'resultCode'?: number;
    'result'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "request",
            "baseName": "request",
            "type": "RawRequest",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": "iso8601"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "resultCode",
            "baseName": "resultCode",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RawResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

