/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InitiationDetails } from '../models/InitiationDetails';
import { Payer } from '../models/Payer';
import { PaymentStatus } from '../models/PaymentStatus';
import { PaymentStatusDetails } from '../models/PaymentStatusDetails';
import { RefundAccount } from '../models/RefundAccount';
import { SubmissionDetails } from '../models/SubmissionDetails';
import { HttpFile } from '../http/http';

export class SubmissionResponse {
    'id'?: string;
    'paymentIdempotencyId'?: string;
    'paymentLifecycleId'?: string;
    'institutionConsentId'?: string;
    'status'?: PaymentStatus;
    'statusDetails'?: PaymentStatusDetails;
    'initiationDetails': InitiationDetails;
    'submissionDetails': SubmissionDetails;
    'payer'?: Payer;
    'refundAccount'?: RefundAccount;
    'expectedExecutionTime'?: Date;
    'expectedSettlementTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentIdempotencyId",
            "baseName": "paymentIdempotencyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentLifecycleId",
            "baseName": "paymentLifecycleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "institutionConsentId",
            "baseName": "institutionConsentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentStatus",
            "format": ""
        },
        {
            "name": "statusDetails",
            "baseName": "statusDetails",
            "type": "PaymentStatusDetails",
            "format": ""
        },
        {
            "name": "initiationDetails",
            "baseName": "initiationDetails",
            "type": "InitiationDetails",
            "format": ""
        },
        {
            "name": "submissionDetails",
            "baseName": "submissionDetails",
            "type": "SubmissionDetails",
            "format": ""
        },
        {
            "name": "payer",
            "baseName": "payer",
            "type": "Payer",
            "format": ""
        },
        {
            "name": "refundAccount",
            "baseName": "refundAccount",
            "type": "RefundAccount",
            "format": ""
        },
        {
            "name": "expectedExecutionTime",
            "baseName": "expectedExecutionTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expectedSettlementTime",
            "baseName": "expectedSettlementTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SubmissionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



