/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { PaymentContextType } from '../models/PaymentContextType';
import { HttpFile } from '../http/http';

/**
* __Mandatory__. The payment request object defining the details of the payment for execution under the Variable Recurring Payment consent.
*/
export class SubmissionRequest {
    /**
    * __Mandatory__. A unique identifier that you must provide to identify the payment. This can be any alpha-numeric string but is limited to a maximum of 35 characters.
    */
    'paymentIdempotencyId': string;
    /**
    * __Mandatory__. Chosen authentication method for submission step. Allowed values are [SCA_REQUIRED, SCA_NOT_REQUIRED].
    */
    'psuAuthenticationMethod': string;
    'contextType'?: PaymentContextType;
    'paymentAmount': Amount;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentIdempotencyId",
            "baseName": "paymentIdempotencyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "psuAuthenticationMethod",
            "baseName": "psuAuthenticationMethod",
            "type": "string",
            "format": ""
        },
        {
            "name": "contextType",
            "baseName": "contextType",
            "type": "PaymentContextType",
            "format": ""
        },
        {
            "name": "paymentAmount",
            "baseName": "paymentAmount",
            "type": "Amount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubmissionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



