/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { HttpFile } from '../http/http';

export class SweepingPeriodicLimits {
    /**
    * __Mandatory__. Maximum amount that can be specified in all payment instructions in a given period under this VRP consent. If the Alignment is Calendar, the limit is pro-rated in the first period to the remaining number of days.
    */
    'totalMaxAmount': Amount;
    /**
    * __Mandatory__. Frequency for which the payment limits are enforced. Allowed values are [DAILY, WEEKLY, FORTNIGHTLY, MONTHLY, YEARLY].
    */
    'frequency': string;
    /**
    * __Mandatory__. Period alignment for which the payment limits are enforced. Allowed values are [CONSENT, CALENDAR]. If CONSENT, then period starts on consent creation date. If CALENDAR, then period lines up with the frequency e.g. WEEKLY period will begin at start of the week in question.
    */
    'alignment': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalMaxAmount",
            "baseName": "totalMaxAmount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "string",
            "format": ""
        },
        {
            "name": "alignment",
            "baseName": "alignment",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SweepingPeriodicLimits.attributeTypeMap;
    }

    public constructor() {
    }
}

