/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The frequency at which transactions occurred.
*/
export class TransactionSchedule {
    /**
    * How often the transaction happens.  Can be \'Monthly\', \'Twice monthly\', \'Every two weeks\', \'Every four weeks\', \'Daily\', \'Weekly\', \'Every weekday\', \'Twice daily\', \'Twice every weekday\'
    */
    'frequency'?: string;
    /**
    * When in the cycle the transaction occurs.  Can be \'Daily\', \'Twice daily\', \'Twice every weekday\', \'Every weekday\', \'Weekly on day n\', \'Every two weeks on day n\', \'Monthly on working day before day n of month\', \'Monthly on last working day of month\', \'Twice a month on 15th and last working day of month\', \'Every four weeks on day n\'
    */
    'detailedFrequency'?: string;
    /**
    * The n in detailedFrequency where there is one - for week-based frequencies, an integer from 0 to 6 where 0 is Monday or for month-based frequencies, an integer from 0 to 27 where 0 is the first day of the month
    */
    'detailedFrequencyParameter'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "string",
            "format": ""
        },
        {
            "name": "detailedFrequency",
            "baseName": "detailedFrequency",
            "type": "string",
            "format": ""
        },
        {
            "name": "detailedFrequencyParameter",
            "baseName": "detailedFrequencyParameter",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}

