/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsentDeleteResponse } from '../models/ConsentDeleteResponse';
import { DeleteStatusEnum } from '../models/DeleteStatusEnum';
import { HttpFile } from '../http/http';

/**
* Deletion of the user. Includes the user profile and all associate consents.
*/
export class UserDeleteResponse {
    /**
    * Unique identifier of the user.
    */
    'id'?: string;
    'deleteStatus'?: DeleteStatusEnum;
    /**
    * Date and time that the user was created.
    */
    'creationDate'?: Date;
    'userConsents'?: Set<ConsentDeleteResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "deleteStatus",
            "baseName": "deleteStatus",
            "type": "DeleteStatusEnum",
            "format": ""
        },
        {
            "name": "creationDate",
            "baseName": "creationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "userConsents",
            "baseName": "userConsents",
            "type": "Set<ConsentDeleteResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserDeleteResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



