/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VirtualAccountPaymentAmount } from '../models/VirtualAccountPaymentAmount';
import { VirtualAccountTransferDestination } from '../models/VirtualAccountTransferDestination';
import { VirtualAccountTransferSource } from '../models/VirtualAccountTransferSource';
import { HttpFile } from '../http/http';

export class VirtualAccountTransferRequest {
    'amount': VirtualAccountPaymentAmount;
    /**
    * Reference to be associated with the transfer. This will be appear on the destination\'s bank statement
    */
    'reference': string;
    'source': VirtualAccountTransferSource;
    'destination': VirtualAccountTransferDestination;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "VirtualAccountPaymentAmount",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "VirtualAccountTransferSource",
            "format": ""
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "VirtualAccountTransferDestination",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirtualAccountTransferRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

