/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VirtualAccountAddress } from '../models/VirtualAccountAddress';
import { VirtualAccountClientBusinessType } from '../models/VirtualAccountClientBusinessType';
import { HttpFile } from '../http/http';

export class VirtualAccountBusinessClient {
    'name': string;
    'type': VirtualAccountClientBusinessType;
    'registrationNumber': string;
    'registeredAddress': VirtualAccountAddress;
    'tradingAddress'?: VirtualAccountAddress;
    'contactName': string;
    'email': string;
    'phone': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "VirtualAccountClientBusinessType",
            "format": ""
        },
        {
            "name": "registrationNumber",
            "baseName": "registrationNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "registeredAddress",
            "baseName": "registeredAddress",
            "type": "VirtualAccountAddress",
            "format": ""
        },
        {
            "name": "tradingAddress",
            "baseName": "tradingAddress",
            "type": "VirtualAccountAddress",
            "format": ""
        },
        {
            "name": "contactName",
            "baseName": "contactName",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirtualAccountBusinessClient.attributeTypeMap;
    }

    public constructor() {
    }
}



