/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountIdentification } from '../models/AccountIdentification';
import { HttpFile } from '../http/http';

export class VirtualAccountPaymentSource {
    /**
    * Type of source for a payment. One of ACCOUNT or EXTERNAL
    */
    'type': string;
    /**
    * Only present if type is ACCOUNT. Identifies the Virtual Account from which the payment was made
    */
    'accountId'?: string;
    /**
    * Only present if type is BENEFICIARY. Identifies the Virtual Account Beneficiary from which the payment was made
    */
    'beneficiaryId'?: string;
    /**
    * Only present if type is EXTERNAL. The account identifications that identify an external source
    */
    'accountIdentifications'?: Set<AccountIdentification>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "beneficiaryId",
            "baseName": "beneficiaryId",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountIdentifications",
            "baseName": "accountIdentifications",
            "type": "Set<AccountIdentification>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirtualAccountPaymentSource.attributeTypeMap;
    }

    public constructor() {
    }
}

