/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VirtualAccountBusinessClient } from '../models/VirtualAccountBusinessClient';
import { VirtualAccountClientStatus } from '../models/VirtualAccountClientStatus';
import { VirtualAccountClientType } from '../models/VirtualAccountClientType';
import { VirtualAccountIndividualClient } from '../models/VirtualAccountIndividualClient';
import { VirtualAccountKycStatus } from '../models/VirtualAccountKycStatus';
import { HttpFile } from '../http/http';

export class VirtualAccountClient {
    /**
    * The id generated in the on-boarding process, it will be used as client-id for virtual accounts request
    */
    'id'?: string;
    'type'?: VirtualAccountClientType;
    'kycStatus'?: VirtualAccountKycStatus;
    'status'?: VirtualAccountClientStatus;
    'createdDateTime'?: Date;
    'individual'?: VirtualAccountIndividualClient;
    'business'?: VirtualAccountBusinessClient;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "VirtualAccountClientType",
            "format": ""
        },
        {
            "name": "kycStatus",
            "baseName": "kycStatus",
            "type": "VirtualAccountKycStatus",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "VirtualAccountClientStatus",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "individual",
            "baseName": "individual",
            "type": "VirtualAccountIndividualClient",
            "format": ""
        },
        {
            "name": "business",
            "baseName": "business",
            "type": "VirtualAccountBusinessClient",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirtualAccountClient.attributeTypeMap;
    }

    public constructor() {
    }
}



