/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VirtualAccountBeneficiaryAccount } from '../models/VirtualAccountBeneficiaryAccount';
import { VirtualAccountBeneficiaryAddress } from '../models/VirtualAccountBeneficiaryAddress';
import { HttpFile } from '../http/http';

export class VirtualAccountBeneficiaryRequest {
    /**
    * Reference that can be provided in order to help with identification of the Beneficiary
    */
    'nickname': string;
    /**
    * Indicates the type of Beneficiary as either an INDIVIDUAL or BUSINESS
    */
    'type': string;
    'name': string;
    'birthDate'?: string;
    /**
    * Beneficiary payment schemes
    */
    'paymentSchemes': Array<string>;
    'address': VirtualAccountBeneficiaryAddress;
    'account': VirtualAccountBeneficiaryAccount;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birthDate",
            "type": "string",
            "format": "date"
        },
        {
            "name": "paymentSchemes",
            "baseName": "paymentSchemes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "VirtualAccountBeneficiaryAddress",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "VirtualAccountBeneficiaryAccount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirtualAccountBeneficiaryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

