/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VirtualAccountPaymentAmount } from '../models/VirtualAccountPaymentAmount';
import { HttpFile } from '../http/http';

export class VirtualAccountPayOutRequest {
    /**
    * Unique id of the source / payer account
    */
    'accountId': string;
    'amount': VirtualAccountPaymentAmount;
    /**
    * Reference to be associated with the payment. This will be appear on the beneficiary\'s bank statement
    */
    'reference': string;
    /**
    * Unique id of the beneficiary to whom the payment will be made
    */
    'beneficiaryId': string;
    /**
    * Method of settlement to complete the payment. One of: <br> FASTER_PAYMENTS <br> SEPA_CREDIT <br> SEPA_INSTANT <br> SWIFT <br> SWIFT_EXPRESS <br> CHAPS <br> IAT <br> WIRE
    */
    'paymentScheme': string;
    /**
    * Date on which a payment instruction will be executed, that must be in the future
    */
    'paymentDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "VirtualAccountPaymentAmount",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "beneficiaryId",
            "baseName": "beneficiaryId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentScheme",
            "baseName": "paymentScheme",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentDate",
            "baseName": "paymentDate",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return VirtualAccountPayOutRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

