/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { VrpPeriodicLimit } from '../models/VrpPeriodicLimit';
import { HttpFile } from '../http/http';

export class VrpConfiguration {
    /**
    * Maximum amount per transaction
    */
    'maximumIndividualAmount'?: Amount;
    /**
    * Maximum cumulative amount
    */
    'maximumCumulativeAmount'?: Amount;
    /**
    * Maximum cumulative number of payments
    */
    'maximumCumulativeNumberOfPayments'?: number;
    'periodicLimits'?: Array<VrpPeriodicLimit>;
    /**
    * Payment Category with allowed values: ONGOING, SUBSCRIPTION
    */
    'recurringPaymentCategory'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maximumIndividualAmount",
            "baseName": "maximumIndividualAmount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "maximumCumulativeAmount",
            "baseName": "maximumCumulativeAmount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "maximumCumulativeNumberOfPayments",
            "baseName": "maximumCumulativeNumberOfPayments",
            "type": "number",
            "format": ""
        },
        {
            "name": "periodicLimits",
            "baseName": "periodicLimits",
            "type": "Array<VrpPeriodicLimit>",
            "format": ""
        },
        {
            "name": "recurringPaymentCategory",
            "baseName": "recurringPaymentCategory",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VrpConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

