/**
 * Yapily API
 * The Yapily API enables connections between your application and users\' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * OpenAPI spec version: 2.30.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from '../models/Amount';
import { HostedVRPLimitsRequest } from '../models/HostedVRPLimitsRequest';
import { Payee } from '../models/Payee';
import { Payer } from '../models/Payer';
import { PaymentRisk } from '../models/PaymentRisk';
import { HttpFile } from '../http/http';

export class VRPSetupRequest {
    'payer'?: Payer;
    'payee': Payee;
    /**
    * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
    */
    'reference'?: string;
    'limits'?: HostedVRPLimitsRequest;
    /**
    * __Optional__. Start date when the consent becomes valid.
    */
    'validFrom'?: Date;
    /**
    * __Optional__. End date when the consent expires and becomes invalid.
    */
    'validTo'?: Date;
    /**
    * The use-case for the VRP consent supported by the bank. Allowed values: <br>`ONGOING` <br>`SUBSCRIPTION`
    */
    'recurringPaymentCategory'?: string;
    /**
    * __Optional__. Initial payment to be charged under this consent. If enforced, this amount must match the first payment amount executed using this consent.
    */
    'initialPayment'?: Amount;
    'risk'?: PaymentRisk;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payer",
            "baseName": "payer",
            "type": "Payer",
            "format": ""
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "Payee",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "limits",
            "baseName": "limits",
            "type": "HostedVRPLimitsRequest",
            "format": ""
        },
        {
            "name": "validFrom",
            "baseName": "validFrom",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "validTo",
            "baseName": "validTo",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "recurringPaymentCategory",
            "baseName": "recurringPaymentCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "initialPayment",
            "baseName": "initialPayment",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "risk",
            "baseName": "risk",
            "type": "PaymentRisk",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VRPSetupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

